-- --- Transform a raw HTML element which contains only a `<break>`
-- -- into a format-indepentent line break.
-- function RawInline (el)
--   if el.format:match '^html' and el.text:match '%<break ?/?%>' then
--     return pandoc.LineBreak()
--   end
-- end